net: http: Fix linking issues with clang
There is a linking failure if using clang and no optimizations

subsys/net/lib/http/http_server_core.c:1060:
   (.text.handle_listen_pollin+0x159):
   undefined reference to `accept_h3_connection'
subsys/net/lib/http/http_server_core.c:1101:
   (.text.handle_listen_pollin+0x425):
   undefined reference to `h3_open_uni_streams'

When CONFIG_NO_OPTIMIZATIONS=y was set.

Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>