drivers: ethernet: esp32: guard eth_esp32_iomux_rmii_clk_input
Add a guard for `eth_esp32_iomux_rmii_clk_input` function to fix the
following error:

error: 'eth_esp32_iomux_rmii_clk_input' defined but not used
[-Werror=unused-function] 245 | static void
eth_esp32_iomux_rmii_clk_input(void)

Signed-off-by: Bartosz Bilas <bartosz.bilas@hotmail.com>